name: Daily Commit

on:
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Make a commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'archejk'
        git config --global user.email 'jkarche13@gmail.com'
        current_time=$(TZ=UTC-8 date '+%a %b %d %T UTC %Y')
        echo "Daily update $current_time" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit $current_time"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/archejk/daily-chirp.git HEAD:main
