name: Dynamic Daily Commits

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Make a commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_ENABLED: ${{ secrets.COMMIT_ENABLED }} # load the secret value created in github
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} # load the secret value created in github
      run: |
        # Check if commit is enabled
        if [ "${COMMIT_ENABLED}" != "true" ]; then
          echo "Commits are disabled via COMMIT_ENABLED secret. Exiting..."
          exit 0
        fi

        RANDOM_NUMBER=$(shuf -i 1-100 -n 1)

        THRESHOLD=25  # Approximately a 25% chance each hour, leading to approximately 6 commits per day on average.

        if [ $RANDOM_NUMBER -le $THRESHOLD ]; then
          echo "Commit threshold met. Proceeding with commit..."
          git config --global user.name 'archejk'
          git config --global user.email 'jkarche13@gmail.com'
          
          # Create a unique commit message with a timestamp
          current_time=$(TZ=UTC-8 date '+%a %b %d %T UTC %Y')
          echo "Daily update $current_time" >> daily_commit.txt
          
          git add daily_commit.txt
          git commit -m "Daily commit $current_time"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/archejk/daily-chirp.git HEAD:main

          # Send alert to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Bot", "content": "✅ Successful commit: Daily commit '"$current_time"'."}' \
               $DISCORD_WEBHOOK_URL
        else
          echo "Skipping commit for this run as threshold not met."
        fi
