name: Dynamic Daily Commits

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Make a commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RANDOM_NUMBER=$(shuf -i 1-100 -n 1)

        THRESHOLD=15  # Approximately a 25% chance each hour

        if [ $RANDOM_NUMBER -le $THRESHOLD ]; then
          git config --global user.name 'archejk'
          git config --global user.email 'jkarche13@gmail.com'
          current_time=$(TZ=UTC-8 date '+%a %b %d %T UTC %Y')
          echo "Daily update $current_time" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/archejk/daily-chirp.git HEAD:main
        else
          echo "Skipping commit for this run"
        fi